/// <reference path="./typings/main.d.ts" />
export let beautylog = require("beautylog");
export let fs = require("fs-extra");
export let lodash = require("lodash");
export let path = require("path");
export let q = require("q");
export let request = require("request");
export let rx = require("rx");
export let shelljs = require("shelljs");
export let smartfile = require("smartfile");
export let smartstring = require("smartstring");
