import "typings-global";
export import beautylog = require("beautylog");
export import childProcess = require("child_process");
export let fs = require("fs-extra");
export let gulp = require("gulp");
export let lodash = require("lodash");
export let moment = require("moment");
export import path = require("path");
export let q = require("q");
export let request = require("request");
export import rxjs = require("rxjs");
export let shelljs = require("shelljs");
export import smartfile = require("smartfile");
export import smartstring = require("smartstring");
export let through2 = require("through2");